name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Cypress test
        uses: cypress-io/github-action@v4.1.0
        with: 
          config-file: cypress.config.ts
          browser: chrome
          headless: true
          command: npm run test
